---
- hosts: staging
  gather_facts: no
  tasks:
    - name: create build directory on the staging machine
      file:
        path: "{{ playbook_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy configuration files Docker on the staging machine
      copy:
        src: Dockerfile
        dest: "{{ playbook_dir }}"
        owner: root
        group: root
        mode: '0644'

    - name: build container image
      docker_image:
        name: mywebapp
        build:
          path: "{{ playbook_dir }}"
        source: build
        state: present

    - name: Add docker_service for the Ansible Container
      become: yes
      docker_container:
        name: My-container
        image: mywebapp
        volumes:
          - "/boxfuse/boxfuse-sample-java-war-hello/target/hello-1.0.war:/tmp/"
        state: present
