---
# tasks file for aws_create
- name: create a new ec2 key pair
   ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: ec2_keypair
    region: "{{ region }}"
   register: keypair

- name: Copy EC2 Private Key locally so it can be later on used to SSH into the instance
  copy: content="{{ keypair.key.private_key }}" dest={{ ec2_key_directory }}key.ppk
  when: keypair.changed == true

- name: Create Ubuntu EC2 instace with public ip
  amazon.aws.ec2_instance:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "{{ keypair }}"
    vpc_subnet_id: subnet-0bd155c67558454b1
    instance_type: "{{ instance_type }}"
    security_group:  [ 'default', "{{ security_group }}" ]
    region: "{{ region }}"
    count: 1
    wait: true
    network:
      assign_public_ip: true
    image: "{{ image }}"
    state: present
    instance_tags:
      name:  ansibleweb
    tags:
      Environment: Testing
    assign_public_ip: yes
  register: ec2_node_info