---
# tasks file for maven
    - name: Install Docker, python3-pip, openJDK and git on the staging machine
      become: true
      apt:
        pkg:
          - docker.io
          - python3-pip
        state: latest
        update_cache: true

    - name: Install docker-compose on the staging machine
      get_url:
        url: "{{ url_docker_compose }}"
        dest: "{{ path_docker_compose }}"
        mode: 'u+x,g+x'
      when: path_docker_compose is not exists

    - name: Install Docker Module for Python on the staging machine
      pip:
        name: docker

    - name: create build directory on the staging machine
      file:
        path: "{{ playbook_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy configuration files Docker on the staging machine
      copy:
        src: '{{ item }}'
        dest: "{{ playbook_dir }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - Dockerfile
        - docker-compose.yml

    - name: Start container using docker-compose on the staging machine
      become: true
      shell:
        cmd: "docker-compose up -d"
      args:
        chdir: "{{ playbook_dir }}"

    - name: Remove the build directory on the staging machine
      ansible.builtin.file:
        path: "{{ playbook_dir }}"
        state: absent
